# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wtYO-H-2NnHlTLwYUB5MqLmBkTcaPut1
"""

import streamlit as st
import pandas as pd

# Cargar datos
datos_a_graficar = pd.DataFrame({'hora': range(24),'recogidas': [random.randint(100, 500) for _ in range(24)]})

# Seleccionar tipo de gráfico
tipo_grafico = st.selectbox("Selecciona el tipo de gráfico", options=["Barras", "Líneas", "Área"])

# Mostrar gráfico basado en selección
if tipo_grafico == "Barras":
    st.bar_chart(datos_a_graficar.set_index("hora")["recogidas"])
elif tipo_grafico == "Líneas":
    st.line_chart(datos_a_graficar.set_index("hora")["recogidas"])
elif tipo_grafico == "Área":
    st.area_chart(datos_a_graficar.set_index("hora")["recogidas"])